### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by fredericof** [geolffreym/p2p-noise#43]
Hello, I'm learning about web3, decentralized protocols, distributed systems and I was interested in your project. How can I help you with this project? Do you have any planned milestones to start to contribute?

**Comment by geolffreym** [comment]
Hey 👋.. sure. Do you use matrix?

**Comment by fredericof** [comment]
> Hey 👋.. sure. Do you use matrix? 

I haven't used it yet. I can try, though.

**Comment by geolffreym** [comment]
Great!! What’s your username?

**Comment by fredericof** [comment]
> Great!! What’s your username?

@fredbitencourt:matrix.org
